# Generated by Django 5.0.6 on 2024-06-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pedidocomida_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
