# Generated by Django 5.0.6 on 2024-06-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ENTREGUE_AUTOMATICAMENTE', 'Entregue_automaticamente'), ('ENTREGUE', 'Entregue'), ('FINALIZADO', 'Finalizado'), ('PENDENTE', 'Pendente')], default='ENTREGUE_AUTOMATICAMENTE', max_length=24),
        ),
    ]
